#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<sys/socket.h>
#include<sys/un.h>
#include<unistd.h>
#include<time.h>

#define SOCKET_NAME "Atishay.socket"

void Error(int a){
	if(a<0){
		perror("Server Down Error\n");
		exit(EXIT_FAILURE);
	}
}

void RandomString(char str[][7]) {        
    srand (time(NULL));                            
    for (int j = 0; j < 50; j++) {
        str[j][0] = j+1;
    }
    
    for(int i = 0; i < 50; i++) {
		for(int j = 1; j <= 5; j++) {
			str[i][j] = rand() % 26 + 65;
		}
	}
}

void printError(int a){
	if(a<0){
		perror("Couldn't create socket");
		exit(EXIT_FAILURE);
	}
}

void writeerror(int a){
	if(a<0){
		perror("Error in writing\n");
		exit(EXIT_FAILURE);
	}
}

void readerror(int a){
	if(a<0){
		perror("Error in read\n");
		exit(EXIT_FAILURE);
	}
}
int main(int argc, char* argv[]) {

	struct sockaddr_un address;
	char strarr[50][7] = {{0}};
	int ret;
	int sockt;
	char buff[7];

	sockt = socket(AF_UNIX, SOCK_SEQPACKET, 0);  // Creating Socket
	printError(sockt);

	memset(&address, 0, sizeof(address));

	// printf("Address is %d\n",address);

	//For local connections
	address.sun_family = AF_UNIX;
	strncpy(address.sun_path, SOCKET_NAME, sizeof(address.sun_path) - 1);
	ret = connect(sockt, (const struct sockaddr *) &address, sizeof(address));

	Error(ret);	

	RandomString(strarr);
	printf("Strings generated by random are: \n");
	for(int i = 0; i <50; i++) {
		for(int j = 0; j < 7; j++) {
			if(j == 0) {
				printf("%d ", strarr[i][j]);
			}
			else printf("%c", strarr[i][j]);
		}
		printf("\n");
	}

	if(argc > 1) {
		strncpy(buff, "DOWN", sizeof("DOWN"));
		write(sockt, buff, sizeof(buff));
		close(sockt);
		exit(EXIT_SUCCESS);
	}
	else {
		int index = 1;
		while(1) {
			printf("Sending strings from %d to %d\n", index, index + 4);
			for(int i = index; i < index + 5; i++) {
				ret = write(sockt, strarr[i], strlen(strarr[i]) + 1);
				writeerror(ret);
			}

			ret = read(sockt, buff, sizeof(buff));
			readerror(ret);

			buff[sizeof(buff) - 1] = 0;
			int finalIdx = atoi(buff);
			
			printf("MAX ID SENT BACK BY SERVER = %s\n\n", buff);
			if(finalIdx == 50) {
				printf("Successfully sent all Strings\n");
				strncpy(buff, "DOWN", sizeof("DOWN"));
				write(sockt, buff, sizeof(buff));
				close(sockt);
				exit(EXIT_SUCCESS);
				break;
			}
			else {
				index = finalIdx + 1;
			}
		}
	}
}